<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RType</AssemblyName>
    <RootNamespace>RType</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Audio\RTypeEngine\**\*.cs" />
    <Compile Remove="Vehicle\DifferentialParameters.cs" />
    <Compile Remove="Tools\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Models\Ek9_Sukimoto\**\*" />
    <None Remove="Assets\Models\Joe'sEK9\**\*" />
    <None Remove="Assets\Tracks\3DTrackBuilderAssets\**\*" />
    <None Remove="Assets\Tracks\AssetoCorsaDownloads\**\*" />
    <None Remove="Assets\Tracks\KN5_Exporter_FBX\**\*" />
    <None Remove="Assets\Sounds\engine-sim-v0.1.14a\**\*" />
    <None Remove="Assets\Sounds\EngineSim\**\*" />
    <None Remove="Assets\Sounds\Honda\HondaB18c5_Uncut.wav" />
    <None Remove="Assets\Sounds\Honda\limiter_8200.wav" />
    <None Remove="Assets\Sounds\Nissan\**\*" />
    <None Remove="Assets\Music\Racing\**\*" />
    <None Remove="ReferenceSource\**\*" />
    <None Update="Data\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Sounds\**\*.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Textures\**\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Menus\**\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Menus\**\*.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Models\**\*.fbx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Models\**\*.FBX">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Models\**\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Models\**\*.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Models\**\*.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Models\**\*.bmp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Models\**\*.rtmesh">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\**\*.mgfxo">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\**\*.fx">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Fonts\**\*.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
